import numpy as np
#help(np.random)
#help(np.random.randn)
#help(np.random.randint)
#help(np.random.ranf)

a=np.random.randn(4)
print(a)
b=np.random.rand(3,4)
print(b)
c=np.random.ranf(3)
print(c)
d=np.random.randint(2,size=20)
print(d)
e=np.random.randint(1,size=20)
print(e)
f=np.random.randint(5,size=20)
print(f)
